runtime: php82
service: default

env_variables:
  DB_HOST: "34.52.242.229"
  DB_NAME: "resto_platform"
  DB_USER: "root"
  DB_PASS: "781155609"
  BASE_URL: "https://sencommandes.ew.r.appspot.com"

# Gestion des fichiers statiques
handlers:
  # Servir les assets statiques
  - url: /assets
    static_dir: assets
    secure: always

  # Servir les uploads
  - url: /uploads
    static_dir: uploads
    secure: always

  # Redirection pour les anciens chemins (compatibilité)
  - url: /resto_plateform/assets
    static_dir: assets
    secure: always

  # Toutes les autres URLs sont gérées par app.php
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: 100ms
  max_concurrent_requests: 50
