runtime: php82
service: default

env_variables:
  DB_HOST: "34.52.242.229"  # IP publique
  DB_NAME: "resto_platform"
  DB_USER: "root"
  DB_PASS: "781155609"
<<<<<<< Updated upstream
  BASE_URL: "https://sencommandes.ew.r.appspot.com/"
  IMG_BASE_PATH: "assets/img/"

handlers:
  # Servir les fichiers PHP directement
  - url: /(.+\.php)$
    script: \1
    secure: always

  # Servir les fichiers statiques
  - url: /(.+\.(gif|png|jpg|jpeg|css|js|ico|webp|svg))$
    static_files: \1
    upload: .+\.(gif|png|jpg|jpeg|css|js|ico|webp|svg)$

  - url: /assets
    static_dir: assets

  - url: /uploads
    static_dir: uploads

  - url: /resto_plateform/assets/(.*)
    static_files: assets/\1
    upload: assets/.*

  # Toutes les autres URLs sont gérées par index.php (pour le routing SPA si nécessaire)
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: 100ms
  max_concurrent_requests: 50

runtime_config:
  document_root: .

health_check:
  enable_health_check: true
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
=======
  DISPLAY_ERRORS: "On"

handlers:
- url: /.*
  script: auto
  secure: always
>>>>>>> Stashed changes
