runtime: php82
service: default

# Ajoutez cette ligne pour utiliser le compte de service GitHub Actions
service_account: github-actions-deploy@[VOTRE_PROJET].iam.gserviceaccount.com

env_variables:
  DB_HOST: "34.52.242.229"
  DB_NAME: "resto_platform"
  DB_USER: "root"
  DB_PASS: "781155609"
  BASE_URL: "https://sencommandes.ew.r.appspot.com/"

handlers:
  - url: /assets
    static_dir: assets
    secure: always

  - url: /(.+\.(gif|png|jpg|css|js|ico|svg))$
    static_files: \1
    upload: .+\.(gif|png|jpg|css|js|ico|svg)$
    secure: always

  - url: /.*
    script: auto
    secure: always
