runtime: php82
service: default

env_variables:
  DB_SOCKET: "/cloudsql/sencommandes:europe-west1:resto-platform-db"
  DB_NAME: "resto_platform"
  DB_USER: "root"
  DB_PASS: "781155609"
  DISPLAY_ERRORS: "On"

handlers:
  # Servir les fichiers statiques directement
  - url: /assets
    static_dir: assets
    secure: always

  - url: /(.+\.(gif|png|jpg|css|js|ico|svg))$
    static_files: \1
    upload: .+\.(gif|png|jpg|css|js|ico|svg)$
    secure: always

  # Router toutes les autres requêtes vers index.php
  - url: /.*
    script: auto
    secure: always

beta_settings:
  cloud_sql_instances: "sencommandes:europe-west1:resto-platform-db"
