runtime: php82
service: default

env_variables:
  DB_HOST: "34.52.242.229"
  DB_NAME: "resto_platform"
  DB_USER: "root"
  DB_PASS: "781155609"  # Ajoutez votre mot de passe ici

# Configuration des handlers pour le routage
handlers:
- url: /(.+\.(gif|png|jpg|jpeg|css|js|ico|webp|svg))$
  static_files: \1
  upload: .+\.(gif|png|jpg|jpeg|css|js|ico|webp|svg)$
  secure: always

- url: /.*
  script: auto
  secure: always

# Configuration des ressources
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Configuration réseau
network:
  session_affinity: true
  name: default

# Configuration de l'échelle automatique
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: 100ms
  max_concurrent_requests: 50
