runtime: php82
service: default

env_variables:
  DB_HOST: "34.52.242.229"
  DB_NAME: "resto_platform"
  DB_USER: "root"
  DB_PASS: "781155609"
  BASE_URL: "https://sencommandes.ew.r.appspot.com/"

handlers:
  # Servir les fichiers statiques directement
  - url: /assets
    static_dir: assets
    secure: always

  - url: /(.+\.(gif|png|jpg|css|js|ico|svg))$
    static_files: \1
    upload: .+\.(gif|png|jpg|css|js|ico|svg)$
    secure: always

  # Router toutes les autres requêtes vers index.php
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: 100ms
  max_concurrent_requests: 50
