steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/resto-platform', '.']
    
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'resto-platform'
    - '--image'
    - 'gcr.io/$PROJECT_ID/resto-platform'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--set-env-vars'
    - 'DB_HOST=34.52.242.229,DB_NAME=resto_platform,DB_USER=root,DB_PASS=781155609,BASE_URL=https://resto-platform-909056157532.europe-west1.run.app/'
    - '--port'
    - '8080'
    - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/resto-platform'
