name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: sencommandes

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: sencommandes

    - name: Build and Deploy to Cloud Run
      run: |-
        gcloud builds submit --config=cloudbuild.yaml .
        gcloud run deploy resto-platform \
          --image gcr.io/sencommandes/resto-platform \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated \
          --port 8080
